### ISSUE TITLE
How to optionally provide an implementation?

### ISSUE THREAD

**Issue by jannic** [rust-embedded/critical-section#25]
Is there a way for a HAL (or similar) to provide a critical-section by default, with the option to disable it if needed?

This would be the most user friendly behavior I can currently think of:
- the HAL crate should provide an implementation by default, so users just need to depend on the HAL to have the implementation activated. (A HAL usually knows the hardware and therefore knows quite well what critical-section implementation would be safe.)
- an optional feature `custom-impl` would disable that default impl. That way, in some special cases, a user might provide an own implementation, eg. if the target is multicore, but the firmware only uses a single core, so a complex and expensive critical-section could be replaced by just disabling interrupts

However, this doesn't work: To be able to implement the critical section, the HAL would need to select on of the `restore-state-*` features of `critical-section`. It is not possible to disable that feature when `custom-impl` is selected. Cargo just provides no way to say "enable this feature of a dependency only if this other dependency is _not_ enabled" (or does it, somehow?).

The second best approach would be:
- the HAL crate should provide an implementation if a default-enabled feature `provide-critical-section-impl` is selected, so users still just need to depend on the HAL to have the implementation activated.
- to be able to provide a custom impl, the dependency on the HAL would need to be declared with `default-features = false`.

This would work, but not well: It's not uncommon that several crates in the dependency tree depend on the HAL. If only one of those forgets to set `default-features = false`, the implementation is included. So a user who wants to provide a custom impl would not only need to add `default-features = false` in one dependency, but might have to hunt down unintended activation of the feature via indirect dependencies.

The remaining option is to just not provide the impl by default, but require a feature to be activated manually. So every binary (but not libraries!) depending on the HAL would need to add `features = [ "provide-critical-section-impl" ]`.

Did I miss any other options? Which approach would meet the intentions of the critical-section authors?

**Comment by Dirbaio** [comment]
I'd say the sanest option is the last one, yes. For all crates that provide an impl, always feature-gate it behind a `critical-section-*` Cargo feature, and *not* enable it by default.

**Comment by jannic** [comment]
For rp2040, we implemented it this way:
- rp2040-hal provides the implementation, feature-gated by the non-default feature `critical-section-impl`
- the BSPs also have a feature with that name, and forward it to the HAL: `critical-section-impl = ["rp2040-hal/critical-section-impl"]`
  - for the BSPs, this feature is default-enabled. The idea is that it's highly unlikely for any crate but the top-level binary to depend on a BSP, so it's easy to disable the default-feature in case it is needed.

That way, we hope to combine good usability for the common case with easy customization for unusual setups.
