### ISSUE TITLE
Remove the (unsound) 0.2.7 impl

### ISSUE THREAD

**Issue by jannic** [rust-embedded/critical-section#30]
Critical-section 1.0 removed all builtin impls, because the default of just disabling interrupts is not appropriate in many cases, and is unsound for multicore systems.

However, there are still crates out there depending on the old version, and it's easy to accidentally include it into the dependency tree. That leads to errors which are difficult to debug. For that reason, the old implementation should be removed from the ecosystem, somehow.

The best way to do this was discussed on [matrix](https://matrix.to/#/#rust-embedded:matrix.org). This ticket tries to summarize the results of those discussions.

One quick and easy approach would be to just yank all 0.2 versions. So that's the baseline. The solution we finally choose should be at least as good as that one. Until yesterday, that was the [planned approach](https://github.com/rust-embedded/wg/blob/master/minutes/2022-11-22.md). But then it was noticed that more crates than expected still depend on it indirectly, mainly by depending on an older version of `atomic-polyfill`. Notably, the latest released version of `heapless` does this.

These are the properties the solution should have, if possible:
- Make sure that nobody accidentally uses the bad default implementation of just disabling interrupts
- Don't make version 0.2.x a required dependency indefinitely, by depending on it from the 1.0/1.1 version
- Don't break existing crates which indirectly depend on the old version of critical-section
  - (It's ok to break crates with only direct dependencies, as they are easily fixed)
- Don't break if there is a manually supplied custom-impl  [^1]

Currently, it looks like most of these can be fulfilled with the following approach:
- Publish a version 0.2.8 of critical section which does
  - Implement the critical-section by using critical-section 1.1 internally, if the RestoreState fits into an u8
  - Only implement `with` (but not `acquire`/`release`) if the RestoreState is larger
-  Yank versions <= 0.2.7

Some WIP experiments are available at https://github.com/rust-embedded/critical-section/pull/29 and https://github.com/jannic/critical-section/tree/reverse-compat2 (no polished code, those branches were just used to exchange ideas while discussing this on matrix.)

[^1]: I'm not sure about this point. It was not discussed yet, and may be misguided. The assumption is that if some crate provides a custom impl of the 0.2 critical-section, it was done on purpose and should be a safe implementation for the target system. This may be overly optimistic.

**Comment by jannic** [comment]
https://github.com/rust-embedded/critical-section/pull/31

**Comment by jannic** [comment]
Is it still useful to actually yank older versions?
It won't apply to projects with an existing Cargo.lock. And new builds without a Cargo.lock would automatically get 0.2.8.
So it would only make a difference for projects with a dependency on a fixed version like `=0.2.7`. I don't think that such a dependency is very likely, and if it's there, it's probably intentional.

**Comment by Dirbaio** [comment]
I'd still say it's useful, it's declaring these versions are unsound and shouldn't be used.

If someone is intentionally doing `=0.2.7` they can easily achieve the same behavior by using `0.2.8` and enabling the right `1.0` impl.

**Comment by Dirbaio** [comment]
This is done already, 0.2.8 removes the builtin unsound impls.
