### ISSUE TITLE
List of critical-section implementations

### ISSUE THREAD

**Issue by wmmc88** [rust-embedded/critical-section#35]
It looks like to use this crate, we need to also provide a critical-section implementation. Do the maintainers of this project know if there is a list of these implementations maintained somewhere? specifically, I'm looking for something that would work on windows with no_std support.

**Comment by adamgreig** [comment]
I've now added a list to the README in #38, but none of them are for Windows - if you're looking for no_std Windows I guess that means inside the kernel, which is probably quite specialist. I don't know anything about the Windows kernel, but maybe it can provide some suitable critical section or exclusive lock? You'll probably need to write something yourself, but you can hopefully take inspiration from the others - it shouldn't be too difficult so long as some sort of concurrency primitive is available...

**Comment by wmmc88** [comment]
> I've now added a list to the README in #38, but none of them are for Windows - if you're looking for no_std Windows I guess that means inside the kernel, which is probably quite specialist. I don't know anything about the Windows kernel, but maybe it can provide some suitable critical section or exclusive lock? You'll probably need to write something yourself, but you can hopefully take inspiration from the others - it shouldn't be too difficult so long as some sort of concurrency primitive is available...

Yup. You're spot on. I wasn't expecting there to be any implementation for my niche case already existing, but was looking for a list to go off of for reference implementations. Thanks!
