### ISSUE TITLE
WebAssembly no_std implementation support

### ISSUE THREAD

**Issue by brandonros** [rust-embedded/critical-section#41]
From what I can tell, this library compiles fine for `wasm32-unknown-unknown` but there is no actual existing implementation (not that I can find on Google?) and you'll end up with

```
 (import "env" "_critical_section_1_0_release" (func $_critical_section_1_0_release))
 (import "env" "_critical_section_1_0_acquire" (func $_critical_section_1_0_acquire))
```

in `wasm-dis` of your output from this error in the browser:

```
Uncaught TypeError: Error resolving module specifier “env”. Relative module specifiers must start with “./”, “../” or “/”.
```

I see in the browser.

I see here WASM support was called out: https://github.com/rust-embedded/critical-section/blob/main/CHANGELOG.md#v022---2021-09-13

I also see a list of implementations in the README: https://github.com/rust-embedded/critical-section/tree/main#usage-in-no-std-binaries

I just don't see one that would work for WASM, so I wanted to make sure I wasn't missing something/wrong that one doesn't exist. If it does exist, maybe it could be added to the README?

**Comment by Dirbaio** [comment]
fwiw the wasm impl in the changelog was the std one: https://github.com/rust-embedded/critical-section/pull/2

0.2 used to auto-enable the right impl based on the target, the change was just to auto-enable the std impl on wasm. On 1.0 you have to explicitly enable `std` .
