### ISSUE TITLE
A mutex type that doesn't disable interrupts while locked

### ISSUE THREAD

**Issue by ia0** [rust-embedded/critical-section#43]
I would like a way to use mutable globals without `unsafe` at usage (i.e. contrary to using `static mut`). I'm in a single core environment and I know that I don't have re-entrancy (i.e. if I have a mutable reference to the global, I will only access it through that reference). I currently have 2 options.

### Option 1: Implement a Mutex type myself

```rust
use portable_atomic::{AtomicBool, Ordering::SeqCst};
static LOCKED: AtomicBool = AtomicBool::new(false);
static mut DATA: FooBar = FooBar::new();
fn lock<R>(operation: impl FnOnce(&mut FooBar) -> R) -> R {
    assert!(!LOCKED.swap(true, SeqCst));
    let result = operation(unsafe { &mut DATA });
    assert!(LOCKED.swap(false, SeqCst));
    result
}
```

This is nice because if interrupts are disabled it's only for a very short amount of time when swapping the atomic bool. But this is not nice because I have to use `unsafe` and implement the whole thing myself. And I'm asking myself: is this even sound?

### Option 2: Use `critical_section::Mutex`

This is nice because I can reuse something existing without `unsafe`. This is not nice because interrupts are disabled for the whole critical operation. If I know there are no re-entrancy issues (and I'm fine panicking if that's the case because it's a bug), I would prefer interrupts to only be disabled during lock and unlock operations, not during the whole critical section.

### Questions

1. Does this assessment make sense? (I'm not even sure the single core requirement is of any use, probably just the re-entrancy is enough, or the guarantee that I won't lock the mutex before next unlock.)
1. Did I miss an existing crate that would solve my problem?
1. Would `critical-section` be a good candidate to provide such feature? (e.g. providing a `PanicMutex` or `SyncRefCell`) Should I ask `portable-atomic` instead? (but the name does not match) Or should it be a different crate altogether?

Thanks a lot!

**Comment by ia0** [comment]
To be more precise, I'm thinking something like this (I would love to know if it's sound, besides knowing if it's useful to others):

```rust
pub struct Mutex<T> {
    lock: AtomicBool,
    data: UnsafeCell<T>,
}
pub struct MutexGuard<'a, T>(&'a Mutex<T>);

unsafe impl<T: Send> Sync for Mutex<T> {}

impl<T> Mutex<T> {
    pub const fn new(data: T) -> Self {
        Mutex { lock: AtomicBool::new(false), data: UnsafeCell::new(data) }
    }

    pub fn try_lock(&self) -> Option<MutexGuard<'_, T>> {
        match self.lock.swap(true, SeqCst) {
            false => Some(MutexGuard(self)),
            true => None,
        }
    }

    pub fn lock(&self) -> MutexGuard<'_, T> {
        self.try_lock().unwrap()
    }
}

impl<'a, T> Deref for MutexGuard<'a, T> {
    type Target = T;

    fn deref(&self) -> &Self::Target {
        unsafe { &*self.0.data.get() }
    }
}

impl<'a, T> DerefMut for MutexGuard<'a, T> {
    fn deref_mut(&mut self) -> &mut Self::Target {
        unsafe { &mut *self.0.data.get() }
    }
}

impl<'a, T> Drop for MutexGuard<'a, T> {
    fn drop(&mut self) {
        assert!(self.0.lock.swap(false, SeqCst));
    }
}
```

**Comment by taiki-e** [comment]
IIUC it seems you need a Mutex that panics instead of spinning or blocking when Mutex is locked from others. I think you could use spin crate's [Mutex::try_lock](https://docs.rs/spin/latest/spin/mutex/struct.Mutex.html#method.try_lock) (with the portable_atomic feature if needed) + unwrap. (You might want to write a wrapper so that you don't accidentally call a method that does the spinning.)

**Comment by ia0** [comment]
Thanks! That's exactly it. And it doesn't change the binary size negatively (actually slightly positively) compared to my implementation provided above.
