### ISSUE TITLE
Release 1.1.3

### ISSUE THREAD

**Issue by chrysn** [rust-embedded/critical-section#48]
Please consider releasing a version 1.1.3.

Not much changed, but the one change has become more urgent in its application: When I sent https://github.com/rust-embedded/critical-section/pull/40, the RIOT project that uses this for its Rust wrappers was far from having a 64bit implementation, but it now works on 64-bit systems as well, and without #40, we have to work around by using a (now larger) maximally sized number.

**Comment by Dirbaio** [comment]
can you send a PR? follow the [last one](https://github.com/rust-embedded/critical-section/pull/39/files), basically updating changelog and version in Cargo.toml
