### ISSUE TITLE
Version `1.1.3` breaks semver rules

### ISSUE THREAD

**Issue by Ddystopia** [rust-embedded/critical-section#51]
Hello, `1.1.3` is a patch version but added a new feature, from changelog:

> Added option to use a usize sized restore state

New feature should be a minor version bump, so `1.1.2 -> 1.2.0`. We were bitten by that, as colleague had `1.1.3` and I had `1.1.2`, and semver (and cargo) allows to go *down* the `patch` change, as they should not add any new features, no api changes, so you should be able to go *down*.

**Comment by adamgreig** [comment]
Thank you for the bug report! You're right and this should have been 1.2.0, apologies. We discussed the issue in our meeting today and concluded that it probably would not have helped you though - cargo will still quietly update to 1.2.0 for you while your colleague still has 1.1.2; either you need to regularly `cargo update` or share `Cargo.lock` in git to resolve this.

Consequently we won't re-release as 1.2.0 for this release, but we'll ensure future minor releases have the correct version number.
